### ISSUE TITLE
InsertToMysqlCourseEnrollByCountryWorkflow

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-analytics-pipeline#11]
Test InsertToMysqlCourseEnrollByCountryWorkflow task

**Comment by dominicfollett** [comment]
Fixed unknown country issue by making sure dat file with geoip data was decompressed.

**Comment by renevatium** [comment]
@dominicfollett that's brilliant. Could you explain that for me please? Decompressed as in ungzipped?

**Comment by dominicfollett** [comment]
@renevatium yes Sir! just made sure it was unzipped, and then imported it into hadoop.
