### ISSUE TITLE
AnswerDistributionWorkflow task

### ISSUE THREAD

**Issue by renevatium** [proversity-org/edx-analytics-pipeline#2]
Test the AnswerDistributionWorkflow (performance) task(s)

**Comment by dominicfollett** [comment]
1. Include a check for zero length package path - this takes care of the `six` issue, although I'm not sure it is a long term fix of any kind. I first started by trying to remove the six package, but it appears it is needed for the task to run. I then tried different version with the same problem. I eventually edited hadoop.py to make the change described above. This appears to be ok. More specifically:
   
   ``` py
   if hasattr(package, "__path__") and len(package.__path__) > 0:
   ```
   
   on line 107 in /var/lib/analytics-tasks/tasks/venv/local/lib/python2.7/site-packages/luigi/hadoop.py. Perhaps the Edx team have provided a solution to this already upstream?
2. Ensure Manifest path is consistent between command line options and override.cfg. Map reduce appears to be going like a Boeing.

**Comment by dominicfollett** [comment]
Update wiki with command: 

```
launch-task AnswerDistributionWorkflow --local-scheduler \
--src s3n://org-proversity-learn/logs/tracking/ \
--dest hdfs://localhost:9000/edx-analytics-pipeline/intermediate/answer_distribution/ 
--name unique_name --output-root hdfs://localhost:9000/edx-analytics-pipeline/intermediate/answer_distribution_output/ 
--include '*tracking.log*' 
--manifest "hdfs://localhost:9000/edx-analytics-pipeline/manifest/" 
--base-input-format "org.edx.hadoop.input.ManifestTextInputFormat" 
--lib-jar "hdfs://localhost:9000/edx-analytics-pipeline/packages/edx-analytics-hadoop-util.jar"
 --n-reduce-tasks 10
 --marker hdfs://localhost:9000/edx-analytics-pipeline/intermediate/dest_marker --credentials /edx/etc/edx-analytics-pipeline/output.json
```

With information added as comments from above.

**Comment by dominicfollett** [comment]
Make sure Manifest is not empty! Threshold should be set to 1.
